trigger:
  - main
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'P2Project/P2Angular'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Angular
  jobs:
  - job:
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'

    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: $(solution)

    - task: Npm@1
      inputs:
        command: 'custom'
        workingDir: $(solution)
        customCommand: 'run build --prod'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(solution)/dist'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'dist'
        publishLocation: 'Container'

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'P2(6b99bb29-57fd-4673-b918-0d515335b837)'
        appType: 'webApp'
        WebAppName: 'PokeLoot'
        deployToSlotOrASE: true
        ResourceGroupName: 'PokeLoot'
        SlotName: 'production'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'



# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(solution)/dist'
#     includeRootFolder: true
#     archiveType: 'zip'
#     archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
#     replaceExistingArchive: true

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     artifactName: 'dist'
#     publishLocation: 'Container'

# - task: AzureRmWebAppDeployment@4
#   inputs:
#     ConnectionType: 'AzureRM'
#     azureSubscription: 'P2(6b99bb29-57fd-4673-b918-0d515335b837)'
#     appType: 'webApp'
#     WebAppName: 'PokeLoot'
#     deployToSlotOrASE: true
#     ResourceGroupName: 'PokeLoot'
#     SlotName: 'production'
#     packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

#packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
